Nome='Baymax'

lista = [["ola", "oi", "eai", "eai?"],
         ["oi, tudo bem?", "oi, tudo bem", "tudo bem?", "tudo bem", "oi, como vai?", "ola, como vai?", "ola, como vai", "como vai?", "como vai", "como vai voce?", "como vai voce"],
         ["bom dia", "bom dia!", "oi, bom dia", "oi, bom dia!", "ola, bom dia", "ola, bom dia!", "eai, bom dia", "eai, bom dia!"],
         ["bom dia, como vai?", "bom dia, como vai", "bom dia, como voce esta?", "bom dia, como voce esta", "bom dia, tudo bem?", "bom dia, tudo bem"],
         ["boa tarde", "boa tarde!", "oi, boa tarde", "oi, boa tarde!", "ola, boa tarde", "ola, boa tarde!", "eai, boa tarde", "eai, boa tarde!"],
         ["boa tarde, como vai?", "boa tarde, como vai", "boa tarde, como voce esta?", "boa tarde, como voce esta", "boa tarde, tudo bem?", "boa tarde, tudo bem"],
         ["boa noite", "boa noite!", "oi, boa noite", "oi, boa noite!", "ola, boa noite", "ola, boa noite!", "eai, boa noite", "eai, boa noite!"],
         ["boa noite, como vai?", "boa noite, como vai", "boa noite, como voce esta?", "boa noite, como voce esta", "boa noite, tudo bem?", "boa noite, tudo bem"],
         ["qual o seu nome?", "qual o seu nome", "pode me falar o seu nome?", "pode me falar o seu nome"],
         ["ajuda", "quero ajuda", "pode me ajudar?", "o que posso fazer?", "o que posso fazer", "pode me ajudar", "informaçoes", "informacoes", "quais as suas funcionalidades", "quais as suas funcionalidades?",],
         ["consulta", "consultas", "plano", "planos", "plano de saude", "planos de saude", "preço", "preco", "preços", "precos", "preços seguradoras", "precos seguradoras", "consulta de planos de saude", "consulta de preços", "consulta de precos", "consulta de preços de seguradoras", "consulta de precos de seguradoras", "consultar os preços das seguradoras", "consultar os precos das seguradora", "quero consultar os preços das seguradoras", "quero consultar os precos das seguradoras"],
         ["covid", "coronavirus", "covid19", "covid-19", "corona", "corona virus"],
         ["casos brasil", "dados brasil", "mortes no brasil", "casos e mortes no brasil", "número de casos e mortes no brasil", "numero de casos e mortes no brasil", "dados covid brasil", "dados coronavirus brasil", "dados covid19 brasil"],
         ["casos mundo", "casos mundiais", "dados mundo", "dados mundiais", "casos e mortes no mundo", "dados covid mundo", "dados coronavirus mundiais", "dados covid19 mundiais",  "dados mundiais do covid", "quero saber os dados mundiais do covid", "gostaria de saber o número de casos do covid no mundo", "gostaria de saber o numero de casos do covid no mundo"],
         ["sintomas", "sintomas do covid", "sintomas coronavirus", "sintomas covid19", "pode me informar os sintomas do covid?", "pode me informar os sintomas do covid", "gostaria de saber os sintomas do covid", "quero saber os sintomas do coronavirus", "quero saber os sintomas do covid19", "quero saber os sintomas do covid"],
         ["prevençao", "prevencao", "prevencao covid", "prevençao covid", "prevencao coronavirus", "prevençao coronavirus", "prevencao covid19", "prevençao covid19", "como posso me prevenir?", "como posso me prevenir", "como me prevenir", "como me prevenir?"],
         ["vou sair" , "sair", "quero sair", "obrigado pela ajuda", "obrigada pela ajuda", "agradeço pela ajuda", "estarei saindo agora"]]


respostas = ["Olá! Como posso ajudar?", 
             "Estou bem! Gostaria que eu te ajudasse em algo?",
             "Bom dia! Como posso ajudar?",
             "Bom dia! Estou muito bem. Como posso ajudar?",
             "Boa tarde! Como posso ajudar?",
             "Boa tarde! Estou muito bem. Como posso ajudar?",
             "Boa noite! Como posso ajudar?",
             "Boa noite! Estou muito bem. Como posso ajudar?",
             "Meu nome é "+Nome+ ". Gostaria de ajuda com alguma coisa?",
             "Você pode pesquisar os preços de planos de saúde de diversas seguradoras do país ou buscar dados e informações sobre o COVID-19",
             "Ok, aguarde só um momento enquanto pesquiso as informações",
             ["O que gostaria de saber sobre o Covid-19","Número de casos e mortes no Brasi","Número de casos e mortes no mundo","sintomas","Prevenção"],
             "\nDados Covid Brasil",
             "\nDados Covid Mundo",
             ["Os principais sintomas do Covid-19 incluem:", "-Dificuldade de respirar;","-Febre;","-Tosse.","Se apresentar estes sintomas, por favor, procure ajuda médica para fazer um exame que poderá comprovar se você tem o COVID-19."],
             ["Algumas das principais recomendações para a prevenção do Covid-19 incluem:","-Higienizar bem as mãos com água e sabão ou álcool gel;","-Quando sair de casa, usar uma  máscara que cubra o nariz e a boca;","-Evitar aglomerações;","-Manter uma distância mínima de ao menos 1 metro de outras pessoas."],
             "Tudo bem. Espero ter sido útil!",
             "Consultar preços\n Sintomas \n Prevenção \n Consultar número de casos"]
