Nome='Baymax'

lista = [["ola", "ola?", "ola!"],
         ["oi", "oi!", "oi?"],
         ["eai", "eai?", "eai!"],
         ["obrigado", "obrigado!", "obrigada", "obrigada!", "muito obrigado", "muito obrigado!", "muito obrigada", "muito obrigada!", "muitissimo obrigado", "muitissimo obrigada", "muitissimo obrigado!", "muitissimo obrigada!", "ok, obrigado", "ok, obrigado!", "ok, muito obrigado", "ok, muito obrigado!", "ok, obrigada", "ok, obrigada!", "ok, muito obrigada", "ok, muito obrigada!"],
         ["agradeco", "agradeco!", "muito agradecido", "muito agradecido!", "muito agradecida", "muito agradecida!"],
         ["alegre", "feliz", "feliz!", "estou feliz", "estou feliz!", "estou muito feliz", "estou muito feliz!", "muito feliz", "muito feliz", "contente", "contente!", "estou contente", "estou contente!", "tambem", "tambem estou bem", "tambem estou muito bem", "estou bem", "estou bem!", "estou muito bem", "estou muito bem!", "indo bem", "indo bem!", "estou indo bem", "estou indo bem!", "estou indo muito bem", "estou indo muito bem!", "bem", "bem!", "muito bem", "muito bem!", "otimo", "estou otimo", "estou otimo!"],
         ["triste", "mal", "chateado", "estou chateado", "nao estou indo muito bem", "nao estou indo bem", "nao estou muito bem", "meio triste", "um pouco triste", "desanimado", "meio desanimado", "um pouco desanimado", "estou triste", "estou meio triste", "estou um pouco triste", "estou desanimado", "estou meio desanimado", "estou um pouco desanimado", "estou mal", "estou um pouco mal"],
         ["oi, tudo bem?", "oi, tudo bem", "tudo bem?", "tudo bem", "oi, como vai?", "ola, como vai?", "ola, como vai", "como vai?", "como vai", "como vai voce?", "como vai voce"],
         ["bom dia", "bom dia!", "oi, bom dia", "oi, bom dia!", "ola, bom dia", "ola, bom dia!", "eai, bom dia", "eai, bom dia!"],
         ["bom dia, como vai?", "bom dia, como vai", "bom dia, como voce esta?", "bom dia, como voce esta", "bom dia, tudo bem?", "bom dia, tudo bem"],
         ["boa tarde", "boa tarde!", "oi, boa tarde", "oi, boa tarde!", "ola, boa tarde", "ola, boa tarde!", "eai, boa tarde", "eai, boa tarde!"],
         ["boa tarde, como vai?", "boa tarde, como vai", "boa tarde, como voce esta?", "boa tarde, como voce esta", "boa tarde, tudo bem?", "boa tarde, tudo bem"],
         ["boa noite", "boa noite!", "oi, boa noite", "oi, boa noite!", "ola, boa noite", "ola, boa noite!", "eai, boa noite", "eai, boa noite!"],
         ["boa noite, como vai?", "boa noite, como vai", "boa noite, como voce esta?", "boa noite, como voce esta", "boa noite, tudo bem?", "boa noite, tudo bem"],
         ["qual e o seu nome?", "qual e o seu nome", "qual era o seu nome mesmo?", "qual era o seu nome mesmo", "qual era o seu nome, mesmo?", "qual era o seu nome, mesmo", "qual o seu nome?", "qual o seu nome", "pode me falar o seu nome?", "pode me falar o seu nome", "pode me dizer o seu nome?", "pode me dizer o seu nome", "poderia me falar o seu nome?", "poderia me falar o seu nome", "poderia me dizer o seu nome?", "poderia me fizer o seu nome", "seu nome", "me fale seu nome", "me diga seu nome", "diga-me o seu nome", "digite o seu nome", "qual seria o seu nome?", "qual seria o seu nome"],
         ["ajuda", "me ajuda", "me ajuda!", "ajude-me", "me ajude", "me ajude!", "quero", "quero ajuda", "pode me ajudar?", "voce me ajuda?", "voce me ajuda", "preciso de ajuda", "o que posso fazer?", "o que posso fazer", "pode me ajudar", "informaçoes", "informacoes", "quais as suas funcionalidades", "quais as suas funcionalidades?"],
         ["consulta", "consultas", "plano", "planos", "plano de saude", "planos de saude", "preço", "preco", "preços", "precos", "preços seguradoras", "precos seguradoras", "consulta de planos de saude", "consulta de preços", "consulta de precos", "consulta de preços de seguradoras", "consulta de precos de seguradoras", "consultar os preços das seguradoras", "consultar os precos das seguradora", "quero consultar os preços das seguradoras", "quero consultar os precos das seguradoras"],
         ["covid", "coronavirus", "covid19", "covid-19", "corona", "corona virus"],
         ["casos brasil", "dados brasil", "mortes no brasil", "casos e mortes no brasil", "número de casos e mortes no brasil", "numero de casos e mortes no brasil", "dados covid brasil", "dados coronavirus brasil", "dados covid19 brasil"],
         ["casos mundo", "casos mundiais", "dados mundo", "dados mundiais", "casos e mortes no mundo", "dados covid mundo", "dados coronavirus mundiais", "dados covid19 mundiais",  "dados mundiais do covid", "quero saber os dados mundiais do covid", "gostaria de saber o número de casos do covid no mundo", "gostaria de saber o numero de casos do covid no mundo"],
         ["sintomas", "sintomas do covid", "sintomas coronavirus", "sintomas covid19", "pode me informar os sintomas do covid?", "pode me informar os sintomas do covid", "gostaria de saber os sintomas do covid", "quero saber os sintomas do coronavirus", "quero saber os sintomas do covid19", "quero saber os sintomas do covid"],
         ["prevençao", "prevencao", "prevencao covid", "prevençao covid", "prevencao coronavirus", "prevençao coronavirus", "prevencao covid19", "prevençao covid19", "como posso me prevenir?", "como posso me prevenir", "como me prevenir", "como me prevenir?"],
         ["vou sair" , "sair", "quero sair", "obrigado pela ajuda", "obrigada pela ajuda", "agradeço pela ajuda", "estarei saindo agora"]]


respostas = ["Olá! Como posso ajudar?",
             "Oi, como posso te ajudar?",
             "Eai, como vai?",
             "De nada! Se precisar de algo, é só me falar.",
             "Eu que agradeço! Se precisar de algo, é só me falar.",
             "Que bom! Então, no que eu poderia ajudar?",
             "Você poderia tentar ouvir umas músicas animadas, elas podem te fazer se sentir melhor.",
             "Estou bem! E você?",
             "Bom dia! Gostaria que eu te ajudasse me algo?",
             "Bom dia! Estou muito bem. Como posso ajudar?",
             "Boa tarde! Como posso ajudar?",
             "Boa tarde! Estou muito bem. Gostaria que eu te ajudasse me algo?",
             "Boa noite! Gostaria que eu te ajudasse me algo?",
             "Boa noite! Estou muito bem. Como posso ajudar?",
             "Meu nome é "+Nome+ ". Gostaria de ajuda com alguma coisa?",
             "Você pode pesquisar os preços de planos de saúde de diversas seguradoras do país ou buscar dados e informações sobre o COVID-19",
             "Ok, aguarde só um momento enquanto pesquiso as informações",
             ["O que gostaria de saber sobre o Covid-19","Número de casos e mortes no Brasi","Número de casos e mortes no mundo","sintomas","Prevenção"],
             "\nDados Covid Brasil",
             "\nDados Covid Mundo",
             ["Os principais sintomas do Covid-19 incluem:", "-Dificuldade de respirar;","-Febre;","-Tosse.","Se apresentar estes sintomas, por favor, procure ajuda médica para fazer um exame que poderá comprovar se você tem o COVID-19."],
             ["Algumas das principais recomendações para a prevenção do Covid-19 incluem:","-Higienizar bem as mãos com água e sabão ou álcool gel;","-Quando sair de casa, usar uma  máscara que cubra o nariz e a boca;","-Evitar aglomerações;","-Manter uma distância mínima de ao menos 1 metro de outras pessoas."],
             "Tudo bem. Espero ter sido útil!"]
